# This file was generated by GoReleaser. DO NOT EDIT.
class Irccloud < Formula
  desc "Text-mode terminal client for IRCCloud."
  homepage ""
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/termoose/irccloud/releases/download/v0.1.2/irccloud_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "970d1be1bd74025a8d5242a521a62e855e4287d0652b5edd30f9b8f81cb19e79"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/termoose/irccloud/releases/download/v0.1.2/irccloud_0.1.2_Linux_x86_64.tar.gz"
      sha256 "aa7c4134d59860dfb086f041992c4b287cec224cc2e4df7b494dc0d05cd6b2b0"
    end
  end

  def install
    bin.install "irccloud"
  end
end
