# This file was generated by GoReleaser. DO NOT EDIT.
class IrccloudCli < Formula
  desc "Text-mode terminal client for IRCCloud"
  homepage "https://github.com/termoose/irccloud"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/termoose/irccloud/releases/download/v0.2.1/irccloud_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "084ccbbdf01a3583a463ae625cb48ef25b2fc9907b5f448feed197268557bb43"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/termoose/irccloud/releases/download/v0.2.1/irccloud_0.2.1_Linux_x86_64.tar.gz"
      sha256 "2b11146995f628b0161f9671922fb32b7454210f4b253654b4d389723ce62bfb"
    end
  end

  def install
    bin.install "irccloud"
  end
end
