# This file was generated by GoReleaser. DO NOT EDIT.
class Irccloud < Formula
  desc "Text-mode terminal client for IRCCloud."
  homepage ""
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/termoose/irccloud/releases/download/v0.1.3/irccloud_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "b0020d57a7af52e7a6eadacab1e821514f41823b71e43a3c5ab66e41ef78f90f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/termoose/irccloud/releases/download/v0.1.3/irccloud_0.1.3_Linux_x86_64.tar.gz"
      sha256 "1ebd3d06c29962c6cdc67a4ba699791cb38c0a23e6d04f0d3de2a6d1cbb3983d"
    end
  end

  def install
    bin.install "irccloud"
  end
end
