# This file was generated by GoReleaser. DO NOT EDIT.
class Skyput < Formula
  desc "File upload utility for Skynet"
  homepage "https://github.com/termoose/skyput"
  version "0.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/termoose/skyput/releases/download/v0.7.0/skyput_0.7.0_Darwin_x86_64.tar.gz"
    sha256 "1a2c32cb3ed124e6767f50830743004f6926d285c35e0a507faf84cd0228c48a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/termoose/skyput/releases/download/v0.7.0/skyput_0.7.0_Linux_x86_64.tar.gz"
      sha256 "b96345dc2437c1b55aee87f393d31b59c780531647f39e1487ab49fb607fe19b"
    end
  end

  def install
    bin.install "skyput"
  end
end
